### ISSUE TITLE
Center - Transparent Background

### ISSUE THREAD

**Issue by rebz** [dumptyd/vue-css-donut-chart#1]
Would be great if the center of the donut had a transparent background. Haven't looked through the code for how it is currently implemented. Using this inside a striped table and want the table color to come through.

**Comment by dumptyd** [comment]
The center is actually an overlay on top of a pie chart to make it look like a donut, so `background-color: inherit;` is not going to work. You can specify the background for it using the [background](https://github.com/dumptyd/vue-css-donut-chart#background) prop.

However, I think I could implement a prop that gets the container's background color using `getComputedStyle` and applies that as the overlay's background.

For now, you can try to modify the behavior using CSS.
```CSS
/* apply !important if necessary */
.striped-table tr:nth-child(even) .cdc-overlay { background-color: 'white'; }
.striped-table tr:nth-child(odd) .cdc-overlay { background-color: 'grey'; }
```
Something like this should work.
